insert into client_information (id, name_owner, agency_code, number_account, digit_verification, register_id) values (1, 'gabrielle mendes de souza', '1234', '5678', '001', '1');
insert into client_information (id, name_owner, agency_code, number_account, digit_verification, register_id) values (2, 'oseas dos santos', '1235', '5679', '002', '2')
insert into client_information (id, name_owner, agency_code, number_account, digit_verification, register_id) values (3, 'josé augusto dias da cruz', '1336', '0051', '003', '3')
insert into client_information (id, name_owner, agency_code, number_account, digit_verification, register_id) values (4, 'ana dias', '0098', '5678', '047', '4')
insert into client_information (id, name_owner, agency_code, number_account, digit_verification, register_id) values (5, 'adriano batista dos santos', '9999', '0789', '150', '5')
insert into client_information (id, name_owner, agency_code, number_account, digit_verification, register_id) values (6, 'luciana ferreira costa', '9632', '8511', '034', '6')
insert into client_information (id, name_owner, agency_code, number_account, digit_verification, register_id) values (7, 'mara cristina carvalho', '1336', '0051', '003', '7')
insert into client_information (id, name_owner, agency_code, number_account, digit_verification, register_id) values (8, 'carolina louis-dreyfuss', '0098', '5678', '999', '8')
insert into client_information (id, name_owner, agency_code, number_account, digit_verification, register_id) values (9, 'viviane moraes', '4785', '0782', '445', '9')
insert into client_information (id, name_owner, agency_code, number_account, digit_verification, register_id) values (10, 'luciano dias dos santos', '9521', '9654', '095', '10')