insert into client_information (id, name_owner, agency_code, number_account, digit_verification, register_id) values (1, 'Gabrielle Mendes de Souza', '1234', '5678', '001', '1')
insert into client_information (id, name_owner, agency_code, number_account, digit_verification, register_id) values (2, 'Oseas dos Santos Cardoso', '1235', '5679', '002', '2')
insert into client_information (id, name_owner, agency_code, number_account, digit_verification, register_id) values (3, 'José Augusto Dias da Cruz', '1336', '0051', '003', '3')
insert into client_information (id, name_owner, agency_code, number_account, digit_verification, register_id) values (4, 'Ana Dias de Mello', '0098', '5678', '047', '4')
insert into client_information (id, name_owner, agency_code, number_account, digit_verification, register_id) values (5, 'Adriano Batista Ferreira', '9999', '0789', '150', '5')
insert into client_information (id, name_owner, agency_code, number_account, digit_verification, register_id) values (6, 'Luciana Ferreira Costa', '9632', '8511', '034', '6')
insert into client_information (id, name_owner, agency_code, number_account, digit_verification, register_id) values (7, 'Mara Cristina Carvalho', '1336', '0051', '003', '7')
insert into client_information (id, name_owner, agency_code, number_account, digit_verification, register_id) values (8, 'Carolina Louis-Dreyfuss', '0098', '5678', '999', '8')
insert into client_information (id, name_owner, agency_code, number_account, digit_verification, register_id) values (9, 'Viviane Pereira Moraes', '4785', '0782', '445', '9')
insert into client_information (id, name_owner, agency_code, number_account, digit_verification, register_id) values (10, 'Luciano Lauro da Silva', '9521', '9654', '095', '10')